services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/filestore
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data: